lakehouse:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: "{{ env_var('SPARK_THRIFT_HOST', 'spark-thrift') }}"
      port: 10000
      schema: gold
      threads: 2
      connect_retries: 10
      connect_timeout: 30
